### ISSUE TITLE
Broken data link in README

### ISSUE THREAD

**Issue by JohnReid** [CSSLab/maia-chess#1]
Hi,

Thanks for your nice paper on MAIA. I was looking for the data you use but the [link](http://csslab.cs.toronto.edu/datasets/chess/kdd2020/) in your README is broken. Is the data available?

Thanks,
John.

**Comment by reidmcy** [comment]
Hi John,

Thanks for telling me. We've been updating the website. I'll fix it this week.

Reid

**Comment by reidmcy** [comment]
The data set is now available with documentation at [csslab.cs.toronto.edu/datasets](http://csslab.cs.toronto.edu/datasets/#maia_kdd). I've also added some of the monthly csvs, and am working on getting all of them. The main issue is the full set is large, over 1 TB, so it's not practical to put them on the FTP server.
