### ISSUE TITLE
How to use it in UCI mode

### ISSUE THREAD

**Issue by cja000** [CSSLab/maia-chess#11]
Hi,

What do you mean with:

> When using the model in UCI mode add nodes 1 when querying as that disables the search.

I only see these parameters for UCI LC0:
```
       _
|   _ | |
|_ |_ |_| v0.26.3 built Oct 10 2020
Detected 6 core(s) and 6 thread(s) in 1 group(s).
Group 0 has 6 core(s) and 6 thread(s).
uci
id name Lc0 v0.26.3
id author The LCZero Authors.
option name WeightsFile type string default <autodiscover>
option name Backend type combo default cuda-auto var cuda-auto var cuda var cuda-fp16 var random var check var recordreplay var roundrobin var multiplexing var demux
option name BackendOptions type string default
option name Threads type spin default 2 min 1 max 128
option name NNCacheSize type spin default 200000 min 0 max 999999999
option name MinibatchSize type spin default 256 min 1 max 1024
option name MaxPrefetch type spin default 32 min 0 max 1024
option name CPuct type string default 2.147000
option name CPuctAtRoot type string default 2.147000
option name CPuctBase type string default 18368.000000
option name CPuctBaseAtRoot type string default 18368.000000
option name CPuctFactor type string default 2.815000
option name CPuctFactorAtRoot type string default 2.815000
option name TwoFoldDraws type check default true
option name VerboseMoveStats type check default false
option name FpuStrategy type combo default reduction var reduction var absolute
option name FpuValue type string default 0.443000
option name FpuStrategyAtRoot type combo default same var reduction var absolute var same
option name FpuValueAtRoot type string default 1.000000
option name CacheHistoryLength type spin default 0 min 0 max 7
option name PolicyTemperature type string default 1.607000
option name MaxCollisionEvents type spin default 32 min 1 max 65536
option name MaxCollisionVisits type spin default 9999 min 1 max 1000000
option name OutOfOrderEval type check default true
option name MaxOutOfOrderEvalsFactor type string default 1.000000
option name StickyEndgames type check default true
option name SyzygyFastPlay type check default true
option name MultiPV type spin default 1 min 1 max 500
option name PerPVCounters type check default false
option name ScoreType type combo default centipawn var centipawn var centipawn_with_drawscore var centipawn_2019 var centipawn_2018 var win_percentage var Q var W-L
option name HistoryFill type combo default fen_only var no var fen_only var always
option name MovesLeftMaxEffect type string default 0.100000
option name MovesLeftThreshold type string default 1.000000
option name MovesLeftSlope type string default 0.005000
option name MovesLeftConstantFactor type string default 0.000000
option name MovesLeftScaledFactor type string default 0.000000
option name MovesLeftQuadraticFactor type string default 1.000000
option name MaxConcurrentSearchers type spin default 1 min 0 max 128
option name DrawScoreSideToMove type spin default 0 min -100 max 100
option name DrawScoreOpponent type spin default 0 min -100 max 100
option name DrawScoreWhite type spin default 0 min -100 max 100
option name DrawScoreBlack type spin default 0 min -100 max 100
option name NodesPerSecondLimit type string default 0.000000
option name SolidTreeThreshold type spin default 100 min 1 max 2000000000
option name SyzygyPath type string default
option name Ponder type check default true
option name UCI_Chess960 type check default false
option name UCI_ShowWDL type check default false
option name UCI_ShowMovesLeft type check default false
option name ConfigFile type string default lc0.config
option name SmartPruningFactor type string default 1.330000
option name SmartPruningMinimumBatches type spin default 0 min 0 max 10000
option name RamLimitMb type spin default 0 min 0 max 100000000
option name MoveOverheadMs type spin default 200 min 0 max 100000000
option name TimeManager type string default legacy
option name LogFile type string default
uciok
```
The nearest one is `NodesPerSecondLimit`

Thank you
C.

**Comment by reidmcy** [comment]
Nodes is part of the [UCI specification](https://www.shredderchess.com/chess-features/uci-universal-chess-interface.html) for the go command, we control it via [python-chess](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.Limit). It's not an option introduced by lc0.

We are working on updating the documentation. This repo was originally intended for replication of the training and scientific aspects of the work, we were not expecting this much attention from the general chess playing community.

**Comment by cja000** [comment]
I see, you mean the `go nodes` same as `go depth` or `go movetime`
Ok, thank you

**Comment by magv** [comment]
@reidmcy, as a related question: could you tell us which lc0 parameters are you using for the maia-bots on lichess, and how are the moves selected? In particular if one uses lc0 with `go nodes` as you recommend in the README, it always selects the same moves for the same position (unsurprisingly), while maia-bots responses have variety (which makes for more interesting games). It is this variety that I'm after.

I'd assume you are setting MultiPV to some high value, and then select randomly one of the reported moves.

**Comment by reidmcy** [comment]
@magv The bots on lichess have an opening book so their first ~10 moves are picked from the empirically observed distribution of human moves. After that we use the neural network to approximate the distribution which is as you noticed deterministic.

The opening book was created in a rush so while it's fine for the bots on Lichess right now. It's not rigorous enough for release right now (and has a custom format). But that will likely change in time

**Comment by magv** [comment]
Thanks, now I understand. Hopefully you'll be able to publish the opening books soon enough too, these would be important for actually using maia.

Is it possible to allow for randomness past the opening? From your paper I understand that maia is trained to predict the top move, not necessarily the move probability distribution, so I'm guessing that not easily. The reason to want further randomness is of course practical: if the player chooses a position-based opening like the London system, the first ~8 moves will be the same every time, and the next ~5 may show very little variation, so it is important for the game not to degenerate into a single line afterwards. (I guess extending the opening books further will help in this regard, but still).

I'd also like to take this opportunity to thank you for this work. Maia is easily the best bot on Lichess for beginners, and beginner-friendly AI in general is sorely lacking at the moment -- less sorely now thanks to you though!

**Comment by reidmcy** [comment]
The Maia engines are neural networks so they output probabilities for every legal move, the engine just picks the best one when making a move. So in theory it's possible for the models to be non-deterministic. I think there are some noise options in lc0 that would do that, but they're designed for self-play training so aren't exactly what we'd want.

Also, the models are also not well calibrated to making low probability moves so it would be a bit less human. For example: they give every move at least a 1-3% chance of occurring.

**Comment by iw6dgm** [comment]
@reidmcy thanks for your explanation.
I have downloaded the final_1100-40.pb.gz network and its config.yml.
I managed to get maia playing under Winboard with lc0 0.23 or 0.26 using those two files above. However, while running some local test against other engines (and against me!), I noticed that - even with the 1100 network - this local version of maia is extremely strong, so I guess I didn't quite manage to reproduce a comparable behaviour to that of the lichess version.
I don't think my hardware can be considered powerful (i7-8565u + Nvidia 1050Ti) but so far it's the only reason I could think of. Am I supposed to use a CPU-only lc0?
Thank you

**Comment by reidmcy** [comment]
You are letting the model search the move tree, that leads to it being a lot stronger. We use the UCI `nodes` command to reduce the search, e.g. `go nodes 1`, `depth 1` should also work. These should be options in your GUI, but you can also try setting the move time as low as possible.

The config files are for the python code in repo so you don't need them. I've updated the docs to make this more clear so hopefully other people won't try to use them.
