### ISSUE TITLE
Inspired!

### ISSUE THREAD

**Issue by DevShy** [CSSLab/maia-chess#12]
Hello good day. I'm a beginner in programming in Brazil, and I got access to the code and I was amazed. I would like to know what your next steps are? Create the Mayan 2000 rating? And is it possible to get an exe from the engine? I await response, I'll be watching!

**Comment by reidmcy** [comment]
Thanks for reaching out, it's great to see how international chess is.

We are currently trying to publish a followup paper, that will be focused on more personalized matching of play style. I will hopefully have time after that to create some higher, and lower rating Maias.

I updated the README with details on how to run Maias locally, [here](https://github.com/CSSLab/maia-chess#how-to-run-maia) so while we still don't have a single exe you can download it should be more clear how to run them locally. i.e. follow the lc0 guide and use one of our weights instead with a low search depth.
