### ISSUE TITLE
Repeated  "how humanly did I play" question during game on Lichess

### ISSUE THREAD

**Issue by shayosler** [CSSLab/maia-chess#13]
In the middle of a [recent game](https://lichess.org/GSdzmY6U) against maia1 on lichess the bot began to repeatedly say

>gg! On a scale from 1 to 5 how humanly did I play? 1 = not human, 5 = very human

![image](https://user-images.githubusercontent.com/3087301/104953851-350d5f00-5995-11eb-8789-e7afbc675832.png)

**Comment by dsjoerg** [comment]
Sounds like the answer is 1, not very human 😃

**Comment by reidmcy** [comment]
Thanks for telling us. It looks like something weird happened with the game. The logs look like this:
```logs/maia-1100.log:2021-01-18 18:40:24,113: Game cleanup: GSdzmY6U
logs/maia-1100.log:2021-01-18 18:40:24,326: Game received: GSdzmY6U
logs/maia-1100.log:2021-01-18 18:40:24,334: Game cleanup: GSdzmY6U
logs/maia-1100.log:2021-01-18 18:40:24,631: Game received: GSdzmY6U
logs/maia-1100.log:2021-01-18 18:40:24,633: Game cleanup: GSdzmY6U
logs/maia-1100.log:2021-01-18 18:40:24,642: Game done successful: GSdzmY6U None
```
I'll try and figure out what caused it

**Comment by shayosler** [comment]
@dsjoerg Haha, I dunno, you could make a case that inane chat spam is pretty human behavior...

**Comment by reidmcy** [comment]
Lichess has changed the chat API, so this shouldn't be an issue anymore
