### ISSUE TITLE
make stand alone distribution  

### ISSUE THREAD

**Issue by msh2050** [CSSLab/maia-chess#15]
it is not clear how to make this work offline...(you need to add more details or instructions on (How to Run Maia) section)
I think it is better to make standalone installation or distribution so we just download and start using...

**Comment by reidmcy** [comment]
Did you read the [Leela quickstart guide](http://lczero.org/play/quickstart/)? What is unclear?

The engines are currently weights for the Leela engine. Making a standalone version would require replicating what they have done, their support of multiple backends is the only reason the Maias works on non-Linux machines.

**Comment by msh2050** [comment]
thanks 
I get more info from this ```
https://github.com/CSSLab/maia-chess/issues/11
```
