### ISSUE TITLE
Decline challenge API

### ISSUE THREAD

**Issue by TBestLittleHelper** [CSSLab/maia-chess#16]
https://lichess.org/api#operation/challengeDecline

There's a new field in the API, to give a reason why it was declined.  Would be lovely if Maia would take advantage of it, since, in particular, there are a few who tries to challenge the bot's to unlimited time control challenges.

**Comment by reidmcy** [comment]
Thanks for telling me. I'm glad to see that proposal has finally been ratified. I'll add support soon

**Comment by reidmcy** [comment]
I've added decline reason although I can't say I'm decline challenges because they're bots so I'll have to see if my issue is address https://github.com/ornicar/lila/issues/7993.
