### ISSUE TITLE
A blunder with Maia 1500 and 1700

### ISSUE THREAD

**Issue by magv** [CSSLab/maia-chess#17]
Hi. So I have encountered a position where Maia 1500 and 1700 both give up a queen, while the rest (including 1100) do not. Is this sort of a thing considered a bug?

The position is this:
```
1r4k1/3b2pp/4p3/Qpq1Pp2/2p2P2/2P1PB2/6PP/4R1K1 b - - 2 26
```

(I also have the full game, if you need that).

You can see the position [on lichess](https://lichess.org/analysis/standard/1r4k1/3b2pp/4p3/Qpq1Pp2/2p2P2/2P1PB2/6PP/4R1K1_b_-_-_2_26). Maia 1500 and 1700 both go b5b4, the rest go d7c6. To be honest, I would be surprised to see any player at all -- much less someone of rating 1700 -- to play b4 here.

**Comment by reidmcy** [comment]
Hi,

Thanks for asking, we don't consider that kind of behaviour a bug.

The way the engines are created is using deep learning, and you can consider them to be trying to find the average move a player (of the targeted rating) would make for a given board. But it's not perfect and if one player made a weird move on a board like that one, or there just aren't many samples "near" it then the engines will perform badly like you've seen. So to fix this issue we'd need to create a new set of models.

One interesting note, is that all the different Maias are trained on totally different data, so them agreeing as much as they do was a surprise to us.
