### ISSUE TITLE
Feature: ask maia to play a certain opening

### ISSUE THREAD

**Issue by had3z** [CSSLab/maia-chess#18]
before the game starts, perhaps maia could accept a parameter with the desired opening it should attempt. things to consider:

- what if maia is black and white goes off script (i ask maia to play italian game (both start with e4-e5) but then white switches it to king's gambit
- perhaps game should start with a predefined position (for king's gambit, e4, e5, f5), and game starts with black to move

this would do wonders for those of us learning openings and trying to navigate the lines

**Comment by clawsoon** [comment]
The easiest way I've found to do this is to run Leela Chess Zero in a local chess GUI with a Maia net loaded.  I've used Nibbler successfully for this:

 - Download and unzip Lc0 to whatever folder you'd like: https://lczero.org/play/download/
 - Download and unzip Nibbler to whatever folder you'd like: https://github.com/fohristiwhirl/nibbler/releases
 - Download the the Maia .pb.gz net that you'd like to play and put it in whatever folder you'd like.
 - Start Nibbler.

In Nibbler:
 - Engine->Choose engine... point to your lc0.exe file from your Lc0 folder.
 - Engine->Choose weights file... point to the Maia .pb.gz file you downloaded.
 - Engine->Node limit - auto-eval/play... set to 1
 - Set up the opening you'd like to play on the board.
 - Versus->Play this colour (or F9)
...and Maia will make the next move to start the game from your preferred opening position.

I've found that sometimes Nibbler halts the engine (especially if I go back to review moves).  In that case, I just need to go back to the latest move and do Versus->Play this colour (or F9) again.

It would be fantastic if Lichess made this an engine you could play like you can play Stockfish, but until it does this seems to be the best option.

**Comment by reidmcy** [comment]
Thanks @clawsoon that's a great explanation of how to get it working.

Building on that you can on Lichess start a game from a position with the engines so while it's not the whole line it is at least an approximation.

But to more directly answer your request, I don't think we can implement opening requests. We only can interact with the opponents via the game chat (and that has issues #13 of its own). So they would have to be done via some kind of chat bot type interface, which would be complicated both in it's UI and in how the bots run (the chat and moves are in different processes).
