### ISSUE TITLE
rematch button for maia bots on lichess.org not working

### ISSUE THREAD

**Issue by Fubs** [CSSLab/maia-chess#27]
The maia bots on lichess no longer accept rematches. A few months ago they would always accept a rematch after a game, but now they don't. I'm not sure the exact day this stopped working, but I think it was sometime in the past few months.

**Comment by reidmcy** [comment]
I believe this is an issue with Lichess (https://github.com/ornicar/lila/issues/9515) that should be fixed in a few days. But I'll double check once they make the update.

**Comment by reidmcy** [comment]
It should be working again the Lichess update has fixed things.
