### ISSUE TITLE
Lichess bots abandoning games

### ISSUE THREAD

**Issue by iostat** [CSSLab/maia-chess#3]
Hey! Not sure if this is the best place to report issues with your lichess bots. I've found that they have a tendency to abandon games. My guess is that you're hitting lichess API rate limits, as your bots seem to be getting quite popular -- so just wanted to flag that in case you weren't aware.

Unless of course that's expected behavior, the 1500 bot did tend to abandon once advantage went 0.5 to me -- which accurately reflects my experience with human 1500s on lichess. In that case, disregard this issue and congrats on passing the chess turing test :P

**Comment by dsjoerg** [comment]
Same, game was abandoned right at the end, I was just about to win!

**Comment by reidmcy** [comment]
This should be fixed now. We were running into some rate limits on Lichess. They were very helpful and raised the limits so all the bots should be working now.
