### ISSUE TITLE
Are the replication-scripts.sh temporarily out of order?

### ISSUE THREAD

**Issue by jinkos** [CSSLab/maia-chess#30]
I have managed to get replication-generate_pgns.sh working but replication-make_leela_files.sh is referencing all sorts of paths that don’t seem to exist (eg /datadrive/pgns_ranged). And when I run it, it has been re-arranging the code files in maia-chess s directory.

I notice in some of the issue posts that there is an update coming, but for the time being should I be expecting these scripts not to work?

**Comment by reidmcy** [comment]
The replication scripts are for replication attempts and are mostly aimed at researchers who want to verify the results. They are basically a dump of my `~/.bash_history` and aren't intended to work on other machines. The [Move Prediction](https://github.com/CSSLab/maia-chess#move-prediction) section has the general instructions for training new models.

These were only trained once so we don't have a nice clean training pipeline, but if you have specific questions about the code/data I'll be happy to answer them.

**Comment by jinkos** [comment]
Ok, so if I apply the move prediction code to the appropriate lichess games, I should - more or less - be able to replicate the Maia bots. Nice.
