### ISSUE TITLE
Background papers

### ISSUE THREAD

**Issue by Dboingue** [CSSLab/maia-chess#35]
I may have dreamed, but it seems that there have been many versions of papers about this project.
I am particularly interested in the version or papers (one I seem to recall looking at, or was it on a website), about figure 11 type of plots from the only paper now mentioned on the readme of this site.

I was impressed by all the preliminary work characterizing lichess data, and using non-deep machine learning or other statistical approach to get a complete set of angles about the data.  I thought it looked solid, and was equally valuable to me as the properties of the maïa engines.

 I hope new paper versions have not trimmed such reporting of background work. It is also giving confidence about the quality of the lichess data.

In particular, I thought there were additional figures of the type that figure 11 shows. but with more detail about the spread of the data points.  Also i am looking for online versions of such figures I could refer to and embed, say here for example or on lichess.

**Comment by reidmcy** [comment]
The code and raw images for our images are in the repo, https://github.com/CSSLab/maia-chess/tree/master/images, we have multiple follow up papers also.
