### ISSUE TITLE
Can you build a Korean chess engine?

### ISSUE THREAD

**Issue by cjssh1002** [CSSLab/maia-chess#39]
Can you build a Korean chess engine?

**Comment by reidmcy** [comment]
The models weights we released use the LC0 engine which has English only documentation (as of last time I checked). That said it communicates via UCI which is a standard interface and there should already be Korean UCI chess GUIs.

We don't have anyone on the team who speaks Korean, so releasing a version in Korean is not something we're looking to do.

**Comment by JohnReid** [comment]
I thought @cjssh1002 might be looking for an engine that plays [Janggi](https://en.wikipedia.org/wiki/Janggi).

**Comment by cjssh1002** [comment]
That's right, English and Korean don't matter. I need the Janggi engine. And there is a GUI that can support it. (Winboard)

**Comment by reidmcy** [comment]
Sorry, I had not heard of Janggi, thanks for introducing me to it. We don't have any plans to expand to other games right now. But the methods we used should work on it if someone else wants to try.
