### ISSUE TITLE
maia disconnects sometimes

### ISSUE THREAD

**Issue by kelvinwop** [CSSLab/maia-chess#4]
![image](https://user-images.githubusercontent.com/30770221/100931436-24ba2700-34b0-11eb-88de-2444198a6a19.png)

**Comment by reidmcy** [comment]
The bots aren't accepting correspondence games, and for the last two days we've had some troubles managing the load as too many people were playing them. They should be much more reliable now, and I'm working on allowing correspondence. Sorry about that
