### ISSUE TITLE
make go fast persistent?

### ISSUE THREAD

**Issue by swpl77** [CSSLab/maia-chess#42]
I'm enjoying playing Maia1.   Nice work!  would it be possible to make the option to go fast stay persistent?   Meaning against any particular user the state remains the same for every game until changed.  I change it at the start of every game.  I have chat disabled and play in zen mode.  So it takes a number of steps to go fast.   Thanks!

**Comment by reidmcy** [comment]
Hi, the way the bots are currently setup this is not possible. We don't track who is playing the bots, so at the start of the game they don't know anything about previous games. Tracking players is not something we're planning on doing right now so remembering the requests is not something we are likely to do soon. It is a good idea, but it's tricky for privacy reasons unfortunately.

**Comment by swpl77** [comment]
got it, thanks!
