### ISSUE TITLE
Could this be used for cheat detection?

### ISSUE THREAD

**Issue by asdfjkl** [CSSLab/maia-chess#43]
With all that cheating debate going on....

I am wondering if Maia or a Maia-like approach could be used to provide additional input to a cheat detection system?

After all, you reported in your papers that with Maia you get much higher human move predictions (depending on rating class) than with say stockfish.

Suppose we take not only the position & rating, but also extra-information such the remaining time of the player into account. Could a network be trained in such a way that the, say top3 move predictions amount to an (80%/90%/almost 100%) move prediction for a given position?

Given a game, this would then provide at least guidance to those positions where a human player (a potential cheater) played moves that the network classifies as "non-human".

Instead of a predictor one could of course also try to create a distiguisher network that given a position and a move tries to predict with a certain amount of probability if that was an engine or computer move...

There might be other creative ways... This might be complete nonsense and not work in practice, but given that you trained Maia and have a much better intuition on what a trained network is capable of, I would like to hear your opinion...

**Comment by asdfjkl** [comment]
I'll have a look into the papers you linked!

>P.S. @asdfjkl I enjoyed your book

wow thanks, that means a lot. I might quote you on that :-)

**Comment by codeisnotfunjk** [comment]
> Something like this is something we've internally talked about a lot, building cheat detection systems for chess, but we don't have any datasets to use for training so publishing a paper would be tricky. If you know of any datasets for chess cheating I'm all ears.

 I have identified a few databases that may be of use to you if you are looking for PGN/moves of Chess matches played between players with ELO ratings of 2000+. 

1. FICS Games: a free resource that offers a large selection of matches and allows you to sort by 2000-2199 ELO, 2200-2399 ELO, etc.- https://www.ficsgames.org/

2. Chessbase: a paid service that provides access to millions of matches played by higher ELO players- https://database.chessbase.com/

3. Lichess: another free option with over 8 million matches, including higher-elo games, sorted by month- https://database.lichess.org/

4. Chesstempo: offers over 2 million searchable games and allows you to sort by min and max ELO in advanced settings- https://old.chesstempo.com/game-database.html

**Comment by codeisnotfunjk** [comment]
> Something like this is something we've internally talked about a lot, building cheat detection systems for chess, but we don't have any datasets to use for training so publishing a paper would be tricky. If you know of any datasets for chess cheating I'm all ears.

I have identified a few databases that may be of use to you if you are looking for PGN/moves of Chess matches played between players with ELO ratings of 2000+. 

1. FICS Games: a free resource that offers a large selection of matches and allows you to sort by 2000-2199 ELO, 2200 ELO-2399, etc.- https://www.ficsgames.org/

2. Chessbase: a paid service that provides access to millions of matches played by higher ELO players- https://database.chessbase.com/

3. Lichess: another free option with over 8 million matches, including higher-elo games, sorted by month- https://database.lichess.org/

4. Chesstempo: offers over 2 million searchable games and allows you to sort by min and max ELO in advanced settings https://old.chesstempo.com/game-database.html

I hope this is of use.

**Comment by reidmcy** [comment]
I am familiar with most of those datasets, I don't think any of them contain information about cheat detection. We also can't easily combine games from different datasets since Elo is not consistent between communities.
