### ISSUE TITLE
is possible to tell maia to play a specific gambit to train?

### ISSUE THREAD

**Issue by mikephung** [CSSLab/maia-chess#45]
hi,
i really want to use maia to train me to know a specific gambit, is possible to do so? In this case how to do that?

**Comment by dahrr** [comment]
If you want to begin the game with the gambit on the board, you can challenge Maia to a "From Position" game on Lichess. Here you can select both your color and the FEN string to start the board with. You can use the Lichess analysis board to generate FEN strings.

**Comment by reidmcy** [comment]
You can also force the model to play an opening with a local version, using an opening book should be possible with most chess GUIs.
