### ISSUE TITLE
What opening books and tablebases would you suggest?

### ISSUE THREAD

**Issue by DarkReaper231** [CSSLab/maia-chess#47]
I have a GUI that supports tablebases and opening books and I am searching all around internet where to get them. But I am rather new in this and I don't know what I should look for.

What opening books and rablebases would suite maia best if I want as many wins as possible for maia?

**Comment by reidmcy** [comment]
Our goal with the project is to build human-like chess engines, not the strongest. If you want a human-like opponent then you should use a tablebase that is based on real human data, not one that is trying to be the strongest.

**Comment by DarkReaper231** [comment]
> Our goal with the project is to build human-like chess engines, not the strongest. If you want a human-like opponent then you should use a tablebase that is based on real human data, not one that is trying to be the strongest.

Yeah I know but is there such tablebase and opening book for download somewhere? A human like?

**Comment by reidmcy** [comment]
I don't have any suggestions for you, I'm sorry. For the bots we use a custom set that I created and aren't public. As my research is focused on AI, I don't use other tablebases.

**Comment by DarkReaper231** [comment]
> I don't have any suggestions for you, I'm sorry. For the bots we use a custom set that I created and aren't public. As my research is focused on AI, I don't use other tablebases.

I eventually settled to Human.bin, It feels humans like. And I chose to not use tablebase as it wouldn't make much sense for Maia anyway.
