### ISSUE TITLE
Unclear instructions/ no instructions for Android

### ISSUE THREAD

**Issue by Allesweter** [CSSLab/maia-chess#48]
I just can't figure out how to install the bot on Android.
I think i need to change network of lc0 to maia-1900, i just don't know how

**Comment by codeisnotfunjk** [comment]
Hello, I am on Android, as well. I am uncertain about how you change it. Where do you go to change the weights file?

**Comment by reidmcy** [comment]
You will likely need to change the weights file using a file-system browser, not an option in the app UI

**Comment by codeisnotfunjk** [comment]
> You will likely need to change the weights file using a file-system browser, not an option in the app UI

You were right. I had to use a file manager app.
