### ISSUE TITLE
Maia1 doesn't accept challenges

### ISSUE THREAD

**Issue by mariusu-msft** [CSSLab/maia-chess#5]
Hi,

Noticing that maia1 does not accept Lichess challenges. Is there an issue with the Bot or only a specific game configuration that it accepts games for?

Thanks,
Marius

**Comment by reidmcy** [comment]
The bots aren't accepting correspondence games, and for the last two days we've had some troubles managing the load as too many people were playing them. They should be much more reliable now, and I'm working on allowing correspondence. Sorry about that
