### ISSUE TITLE
how to use the model

### ISSUE THREAD

**Issue by Tenshi0x0** [CSSLab/maia-chess#52]
hello! I would like to know how to use the model(the.pb file) in your project. The step i should do is load the model in the program, pass parameters to the model about the current board and get the best move. Do i need to clone all the project to local, or I only need to use a piece of code? Looking forward to your early reply!(only used in education project)

**Comment by reidmcy** [comment]
They use the standard UCI interface provided by `lc0`. There are instructions [here](https://github.com/CSSLab/maia-chess#how-to-run-maia), let me know if something in them is unclear.
