### ISSUE TITLE
Replication on Windows

### ISSUE THREAD

**Issue by CallOn84** [CSSLab/maia-chess#54]
Hello everyone.

Firstly, congratulations on the Maia Chess project. I've been watching Maia Chess run on Lichess and it's very impressive.

From what it looks like, you've only run the code on Linux, but I'm on a Windows machine. Anyone successfully trained Maia Chess on a Windows machine?

I do have some experience in training Leela Chess Zero on Windows, as I trained my own version of Leela Chess Zero a while ago, so there's a part of me that the process between the two might be similar.

Kind regards,

CallOn84

**Comment by reidmcy** [comment]
As long as you have tensorflow setup correctly, and with the correct version, then training on windows shouldn't be much different than on a Unix system. If you have specific questions about the training process I can answer them.

**Comment by CallOn84** [comment]
> As long as you have tensorflow setup correctly, and with the correct version, then training on windows shouldn't be much different than on a Unix system. If you have specific questions about the training process I can answer them.

I'm just trying to figure out what ` move_prediction/replication-make_leela_files.sh` and `move_prediction/replication-generate_pgns.sh` would translate to CMD.

**Comment by CallOn84** [comment]
Actually, I've figured it out.
