### ISSUE TITLE
what if stretching 'min ply' parameter

### ISSUE THREAD

**Issue by canaytore** [CSSLab/maia-chess#59]
First of all, I have to say that I am impressed by the beautiful work here and wish you to keep up the good work

It was indicated in the paper that the first 10 'ply' were discarded to ignore most memorized opening moves. I wonder in which part of the codebase it was hardcoded? Have you ever thought about what it would be like if we trained this model for some chess variants where the first 'ply's are significant and vary between ratings?

**Comment by reidmcy** [comment]
We only discarded the openings for evaluating the models. During training we only drop moves when the clock is below 30 seconds. Openings are very important, but deciding which to pick is based on the player's preferences not just skill so it's a very noisy thing to predict. We looked into it a bit more with our followup paper https://arxiv.org/abs/2008.10086, figure 2 shows accuracy on the openings for the predicted Maia model.
