### ISSUE TITLE
Model Not Found Error

### ISSUE THREAD

**Issue by EaswarGn** [CSSLab/maia-chess#68]
I was trying to load the maia-1900 model in order to use it for transfer learning, this is the code that I used to load the model:
```
#custom Keras layer to wrap the TensorFlow SavedModel
class TFSMLayer(Layer):
    def __init__(self, model_path, call_endpoint='serving_default', **kwargs):
        super(TFSMLayer, self).__init__(**kwargs)
        print(model_path)
        self.model = tf.saved_model.load("maia-1900")
        self.call_endpoint = call_endpoint

    def call(self, inputs):
        infer = self.model.signatures[self.call_endpoint]
        return infer(inputs)['output_0'] 
```

The model is saved as 'maia-1900.pb' in the same directory. And I kept getting this error:
```
/opt/homebrew/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
maia-1900.pb
Traceback (most recent call last):
  File "/Users/easwar/Downloads/ChessCNN/transfer_learning.py", line 72, in <module>
    pretrained_output = TFSMLayer('maia-1900.pb')(fen_input)  # Adjust input as needed
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/easwar/Downloads/ChessCNN/transfer_learning.py", line 17, in __init__
    self.model = tf.saved_model.load(model_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/tensorflow/python/saved_model/load.py", line 912, in load
    result = load_partial(export_dir, None, tags, options)["root"]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/tensorflow/python/saved_model/load.py", line 1016, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: maia-1900.pb/{saved_model.pbtxt|saved_model.pb}
```

Please tell me how to fix this, I think that I am not loading the model correctly and if that is the case please tell me how to properly load the model for tensorflow.

**Comment by reidmcy** [comment]
The model weights in this repo are not in the tensorflow format, they are in the lc0 format, you'll need to use the lc0 loader.

Our followup paper does transfer learning and has models in the TF format, starting with that would likely be easier: https://github.com/CSSLab/maia-individual .

**Comment by EaswarGn** [comment]
> The model weights in this repo are not in the tensorflow format, they are in the lc0 format, you'll need to use the lc0 loader.
> 
> Our followup paper does transfer learning and has models in the TF format, starting with that would likely be easier: https://github.com/CSSLab/maia-individual .

I tried running the same code with those models (eg. [final_1900-40](https://github.com/CSSLab/maia-individual/blob/main/models/maia-1900/final_1900-40.pb.gz)) but I still get the same error when trying to load the model. Also, how would I use an lc0 loader to load the model for transfer learning with tensorflow?
