### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by RoundingExplorer** [CSSLab/maia-chess#9]
I am not being able to understand readme. Too complex
Can it be explained in a simpler way

**Comment by BhurkeSiddhesh** [comment]
Same here, I am still trying to figure out the code what works where? Readme is at a higher level, finding it difficult to learn.

**Comment by reidmcy** [comment]
We are working on having a cleaner instructions on running the bots locally. I should have an update once the holidays are over.

**Comment by reidmcy** [comment]
I updated the README with details on how to run Maias locally, [here](https://github.com/CSSLab/maia-chess#how-to-run-maia) so while we still don't have a single exe you can download it should be more clear how to run them locally. i.e. follow the lc0 guide and use one of our weights instead with a low search depth. If you still have issue please open another issue
